name: CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Кэширование node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: nm-${{ hashFiles('yarn.lock') }}
        restore-keys: nm
    - name: Сборка приложения
      run: |
        yarn install
        yarn build
    - name: Подготовка к деплою
      run: |
        mkdir ~/.ssh
        chmod 600 masterkey.pem
        ssh-keyscan -t rsa wtfgames.ru > ~/.ssh/known_hosts
    - name: Деплой production-версии
      if: github.ref == 'master'
      run: rsync -rvz --delete -e 'ssh -i masterkey.pem' \
        ./build/ landmaster@wtfgames.ru:mfo/master/
    - name: Деплой dev-версии
      if: github.ref == 'dev'
      run: rsync -rvz --delete -e 'ssh -i masterkey.pem' \
        ./build/ landmaster@wtfgames.ru:mfo/dev/
