name: CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Кэширование node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: nm-${{ hashFiles('yarn.lock') }}
        restore-keys: nm
    - name: Сборка приложения
      run: |
        yarn install
        yarn build
    - name: Подготовка к деплою
      run: |
        mkdir ~/.ssh
        chmod 600 masterkey.pem
        ssh-keyscan -t rsa 95.217.162.46 > ~/.ssh/known_hosts
    - name: Деплой production-версии
      if: github.ref == 'refs/heads/master'
      run: rsync -rvz --delete -e 'ssh -i masterkey.pem' build/ mfo@95.217.162.46:landing/
    - name: Деплой dev-версии
      if: github.ref == 'refs/heads/dev'
      run: rsync -rvz --delete -e 'ssh -i masterkey.pem' build/ mfo@95.217.162.46:dev/
